### ISSUE TITLE
[BUG] Import error on syntax hide_classified_parts

### ISSUE THREAD

**Issue by mxie1563** [ArasLabs/access-control-examples#1]
## Expected Behavior
Import the policy following the instructions, should work without error

## Actual Behavior
It stopped at one of the provided file
<Item type='ItemType' action='get' select='id'><name>mp_MacPolicyControlledType</name><Relationships><Item type='Property' action='get' select='name'/><Item type='RelationshipType' action='get' select='name'/></Relationships></Item>
  was obtained fro          ****ErrorMessage****
       Filter_xml field validation failed: 
The element 'or' has invalid child element 'method_call'. List of possible elements expected: 'null, eq, ne, gt, lt, ge, le, and, or, not, like'.

          ********************

## Steps to Reproduce 
Just import it, you will see.

1. 
2. 
3. 

### Aras Innovator 
* Major version: 
* Service pack(s): 

### Browsers

- [ ] Internet Explorer 11
- [ ] Firefox ESR 
- [ ] Chrome 
- [ ] Edge 

### Project Version
**What version of this project are you using? Ex: v1.1.0**

## Workaround / Solution
**Have you found a workaround or solution to this issue?**

## Collaboration
**Are you willing to collaborate on this feature? Ex: sharing code, submitting a pull request, testing, etc.**

**Comment by EliJDonahue** [comment]
@asebastian-aras, can you check this out?

@mxie1563 - Can you confirm which service pack of Aras Innovator 11.0 you're using?

**Comment by mxie1563** [comment]
Not sure how to apply service pack and where to get service pack. I have checked the Aras Innovator, here is the info:
Aras Innovator Version 11.0 SP12  Build: 6920
MS Build Number: 000000.00

**Comment by asebastian-aras** [comment]
Hi @mxie1563 
This project was built and tested using 11.0 SP15. Unfortunately DAC Policies were added in SP15, and changes were made to the MAC Policy data structure in 11.0 SP14. This means that the following project will only work on Aras Innovator versions 11.0 SP15+. Although you won't be able to install the examples from this repository directly, [this blog post](https://community.aras.com/b/english/posts/implementing-mac-policies) goes over how you could implement similar MAC Policies within your instance.
AJ
